### ISSUE TITLE
Install issue, internal/util/inspect.js:31 const types = internalBinding('types');

### ISSUE THREAD

**Issue by theapplegates** [kimfucious/kbj#21]
I get an error when I try to install. I am not a developer, so I am not sure what to do. The code is old, so I am not sure if I should update every gem or how should I approach things?

Here is the error.
~/sakura# yarn install-theme
yarn run v1.22.4
$ gulp install
internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/root/sakura/node_modules/natives/index.js:137:5)
    at require (/root/sakura/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/root/sakura/node_modules/natives/index.js:137:5)
    at require (/root/sakura/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/root/sakura/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/root/sakura/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/root/sakura/node_modules/gulp/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by theapplegates** [comment]
I managed to get it working. I’m going to close this. Thanks.
